"""add vehicle_models table

Revision ID: 610abc0ad970
Revises: 4c4043e2d39b
Create Date: 2026-03-20 23:50:02.433500-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610abc0ad970'
down_revision: Union[str, None] = '4c4043e2d39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_vehicle_model_store_name')
    )
    op.create_index(op.f('ix_vehicle_models_store_id'), 'vehicle_models', ['store_id'], unique=False)
    op.alter_column('access_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('access_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_access_logs_created_at'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.alter_column('consultants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dealerships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('service_orders', 'requires_invoice',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_service_orders_entry_time'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_store_status'), table_name='service_orders')
    op.drop_constraint(op.f('service_orders_order_number_key'), 'service_orders', type_='unique')
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stores', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('stores_code_key'), 'stores', type_='unique')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('stores_code_key'), 'stores', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('stores', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('service_orders_order_number_key'), 'service_orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_service_orders_store_status'), 'service_orders', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_service_orders_entry_time'), 'service_orders', ['entry_time'], unique=False)
    op.alter_column('service_orders', 'requires_invoice',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dealerships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('consultants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_access_logs_created_at'), 'access_logs', ['created_at'], unique=False)
    op.alter_column('access_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('access_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_vehicle_models_store_id'), table_name='vehicle_models')
    op.drop_table('vehicle_models')
    # ### end Alembic commands ###
