"""add_service_date_is_verified_verified_at_to_service_orders

Revision ID: c9bc636ab5ab
Revises: 1f521fe1f241
Create Date: 2026-03-25 20:21:44.185156-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bc636ab5ab'
down_revision: Union[str, None] = '1f521fe1f241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('service_date', sa.Date(), nullable=True))
    op.add_column('service_orders', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('service_orders', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'verified_at')
    op.drop_column('service_orders', 'is_verified')
    op.drop_column('service_orders', 'service_date')
    # ### end Alembic commands ###
