"""add_damage_photos_to_service_orders

Revision ID: f86b335c4baa
Revises: eb1c636616ce
Create Date: 2026-04-07 12:22:06.937472-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86b335c4baa'
down_revision: Union[str, None] = 'eb1c636616ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module')
    )
    op.create_index(op.f('ix_user_module_permissions_user_id'), 'user_module_permissions', ['user_id'], unique=False)
    op.create_table('user_store_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'store_id')
    )
    op.drop_index(op.f('ix_apmp_profile_id'), table_name='access_profile_module_permissions')
    op.create_index(op.f('ix_access_profile_module_permissions_profile_id'), 'access_profile_module_permissions', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_access_profiles_is_active'), table_name='access_profiles')
    op.drop_constraint(op.f('uq_access_profiles_name'), 'access_profiles', type_='unique')
    op.drop_constraint(op.f('uq_brands_code'), 'brands', type_='unique')
    op.add_column('service_orders', sa.Column('damage_photos', sa.Text(), nullable=True))
    op.drop_index(op.f('uq_service_code_brand_dept'), table_name='services', postgresql_where='((code IS NOT NULL) AND (is_active = true))')
    op.drop_index(op.f('uq_vehicle_model_brand_name'), table_name='vehicle_models', postgresql_where='(is_active = true)')
    op.create_unique_constraint('uq_vehicle_model_brand_name', 'vehicle_models', ['brand_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vehicle_model_brand_name', 'vehicle_models', type_='unique')
    op.create_index(op.f('uq_vehicle_model_brand_name'), 'vehicle_models', ['brand_id', 'name'], unique=True, postgresql_where='(is_active = true)')
    op.create_index(op.f('uq_service_code_brand_dept'), 'services', ['code', 'brand_id', 'department'], unique=True, postgresql_where='((code IS NOT NULL) AND (is_active = true))')
    op.drop_column('service_orders', 'damage_photos')
    op.create_unique_constraint(op.f('uq_brands_code'), 'brands', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_access_profiles_name'), 'access_profiles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_access_profiles_is_active'), 'access_profiles', ['is_active'], unique=False)
    op.drop_index(op.f('ix_access_profile_module_permissions_profile_id'), table_name='access_profile_module_permissions')
    op.create_index(op.f('ix_apmp_profile_id'), 'access_profile_module_permissions', ['profile_id'], unique=False)
    op.drop_table('user_store_access')
    op.drop_index(op.f('ix_user_module_permissions_user_id'), table_name='user_module_permissions')
    op.drop_table('user_module_permissions')
    # ### end Alembic commands ###
