"""add_user_module_permissions_and_store_access

Revision ID: 1f521fe1f241
Revises: 029
Create Date: 2026-03-21 15:09:54.353428-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f521fe1f241'
down_revision: Union[str, None] = '029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module')
    )
    op.create_index(op.f('ix_user_module_permissions_user_id'), 'user_module_permissions', ['user_id'], unique=False)
    op.create_table('user_store_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'store_id')
    )
    op.drop_index(op.f('uq_services_name_department_brand'), table_name='services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_services_name_department_brand'), 'services', ['name', 'department', sa.literal_column("COALESCE(brand, ''::character varying)")], unique=True)
    op.drop_table('user_store_access')
    op.drop_index(op.f('ix_user_module_permissions_user_id'), table_name='user_module_permissions')
    op.drop_table('user_module_permissions')
    # ### end Alembic commands ###
